parameters:
#    pagos.example.class: FusionClone\PagosBundle\Example

services:
#    pagos.example:
#        class: %pagos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
