parameters:
#    facturas.example.class: FusionClone\FacturasBundle\Example

services:
#    facturas.example:
#        class: %facturas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
