parameters:
#    otros.example.class: FusionClone\OtrosBundle\Example

services:
#    otros.example:
#        class: %otros.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
